server:
  port: 8090
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsystem
    username: postgres
    password: postgres
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
